name: Run Naukri Profile Update

on:
  schedule:
    - cron: "0 2 * * *" # Runs daily at 8 AM UTC (convert to UTC from your local time)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the script
        run: |
          python src/update_naukri_profile.py